### ISSUE TITLE
Production Build

### ISSUE THREAD

**Issue by jacekschae** [gothinkster/angular-realworld-example-app#88] opened 2018-03-22 08:57 UTC
I'm about to update the [RealWorld Comparison](https://medium.freecodecamp.org/a-real-world-comparison-of-front-end-frameworks-with-benchmarks-e1cb62fd526c).

Is there any possibility that we could have in the repo production build? Just as ELM has one with time traveling and another with production?

I'm not Angular expert and would prefer to not deploy this on my own,

Thanks for considering,

**Comment by hamzahamidi** [comment] 2018-04-03 18:55
@jacekschae  To generate the production build run the following command:
```ng build --prod```

**Comment by juristr** [comment] 2018-04-05 08:24
Duplicate of #92. Please consider discussing this over there.

**Closed by juristr** 2018-04-05 08:24 UTC
