### ISSUE TITLE
 this[kHandle] = new _Hash(algorithm, xofLen); error

### ISSUE THREAD

**Issue by HamzaErraji** [gothinkster/angular-realworld-example-app#240] opened 2022-12-08 01:03 UTC
I runned  the commands yarn install then ng serve. I got these errors

```
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/t/Bureau/try/new/angular-realworld-example-app/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/t/Bureau/try/new/angular-realworld-example-app/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/t/Bureau/try/new/angular-realworld-example-app/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/t/Bureau/try/new/angular-realworld-example-app/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/t/Bureau/try/new/angular-realworld-example-app/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/t/Bureau/try/new/angular-realworld-example-app/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/t/Bureau/try/new/angular-realworld-example-app/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/t/Bureau/try/new/angular-realworld-example-app/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/t/Bureau/try/new/angular-realworld-example-app/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/Users/t/Bureau/try/new/angular-realworld-example-app/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.loader (/Users/t/Bureau/try/new/angular-realworld-example-app/node_modules/css-loader/dist/index.js:183:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

**Comment by srinivaskacham** [comment] 2023-03-13 19:18
Any solution for the above issue?

**Comment by geromegrignon** [comment] 2023-04-14 12:32
Hello, the project has been updated lately.
I followed the steps provided but i can't reproduce the issue.

I'm closing it, feel free to reopen it if required

**Closed by geromegrignon** 2023-04-14 12:32 UTC
